; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:esp32doit-devkit-v1]
; platform = espressif32
; board = esp32doit-devkit-v1
; framework = arduino



[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

build_flags = 
    -I${platformio.include_dir}
    -I${platformio.include_dir}/sensors
    -I${platformio.include_dir}/utils
    -I${PLATFORMIO_HOME_DIR}/packages/framework-espidf/components/driver/include
    -I${PLATFORMIO_HOME_DIR}/packages/framework-espidf/components/esp_common/include
    -I${PLATFORMIO_HOME_DIR}/packages/framework-espidf/components/esp_system/include
    -I${PLATFORMIO_HOME_DIR}/packages/framework-espidf/components/freertos/FreeRTOS-Kernel/include
    -I${PLATFORMIO_HOME_DIR}/packages/framework-espidf/components/freertos/esp_additions/include/freertos
    -I${PLATFORMIO_HOME_DIR}/packages/framework-espidf/components/hal/include
    -I${PLATFORMIO_HOME_DIR}/packages/framework-espidf/components/soc/esp32/include
    -I${PLATFORMIO_HOME_DIR}/packages/framework-espidf/components/heap/include
    -I${PLATFORMIO_HOME_DIR}/packages/framework-espidf/components/log/include

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_type = debug